/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crypto_algo_neoscrypt_hasher */

#ifndef _Included_com_crypto_algo_neoscrypt_hasher
#define _Included_com_crypto_algo_neoscrypt_hasher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crypto_algo_neoscrypt_hasher
 * Method:    neoscrypt
 * Signature: ([C[CI)[C
 */
JNIEXPORT jcharArray JNICALL Java_com_crypto_algo_neoscrypt_hasher_neoscrypt
  (JNIEnv *, jobject, jcharArray, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
